"""Markdown rendering helpers extracted from json_tools.py.

Each function writes a specific section of the generated Markdown,
making the overall rendering pipeline easier to understand and test.
"""

import os
import re
from collections import defaultdict

from .paper_links import ensure_paper_record, render_paper_row


def pretty_math(s: str) -> str:
    """Process ALL math expressions ($...$) in the string.

    Strips leading/trailing whitespace inside each $...$ block and
    ensures proper spacing around math expressions.
    """
    result = ""
    last_end = 0
    for match in re.finditer(r"\$.*?\$", s):
        start, end = match.span()
        # Append text before this match
        result += s[last_end:start]
        # Determine spacing
        space_before = ""
        if start > 0 and s[start - 1] not in (" ", "*"):
            space_before = " "
        space_after = ""
        if end < len(s) and s[end] not in (" ", "*"):
            space_after = " "
        inner = match.group()[1:-1].strip()
        result += f"{space_before}${inner}${space_after}"
        last_end = end
    result += s[last_end:]
    return result if result else s


def sort_papers(papers: dict) -> dict:
    """Sort papers by key in reverse order (newest first)."""
    output = {}
    keys = sorted(papers.keys(), reverse=True)
    for key in keys:
        output[key] = papers[key]
    return output


def group_papers_by_month(papers: dict) -> dict:
    """Group papers by YYYY-MM date string."""
    grouped = defaultdict(dict)
    for paper_id, entry in sort_papers(papers).items():
        record = ensure_paper_record(entry, paper_id=paper_id)
        grouped[record["date"][:7]][paper_id] = record
    return dict(grouped)


def write_badge_section(f) -> None:
    """Write the GitHub badge rows."""
    f.write("![paper-list](https://github.com/isLinXu/issues/assets/59380685/dbd27f25-e7d7-4a0f-bdc2-d9b06fc03a2e) ")
    f.write("![GitHub stars](https://img.shields.io/github/stars/isLinXu/paper-list?style=flat-square&color=ffd700) ")
    f.write("![GitHub forks](https://img.shields.io/github/forks/isLinXu/paper-list?style=flat-square&color=4ecdc4) ")
    f.write("![GitHub watchers](https://img.shields.io/github/watchers/isLinXu/paper-list?style=flat-square&color=ff6b6b)\n")
    f.write("[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fatrox%2Fsync-dotenv%2Fbadge&style=flat-square)](https://github.com/isLinXu/paper-list) ")
    f.write("![GitHub last commit](https://img.shields.io/github/last-commit/isLinXu/paper-list?style=flat-square&color=a8e6cf) ")
    f.write("![GitHub repo size](https://img.shields.io/github/repo-size/isLinXu/paper-list.svg?style=flat-square&color=ffd3b6) ")
    f.write("![GitHub language count](https://img.shields.io/github/languages/count/isLinXu/paper-list?style=flat-square&color=ffaaa5)\n")
    f.write("![GitHub](https://img.shields.io/github/license/isLinXu/paper-list.svg?style=flat-square&color=c7ceea) ")
    f.write("![Hits](https://hits.dwyl.com/isLinXu/paper-list.svg?style=flat-square&color=95e1d3)\n")


def write_title_header(f, date_now: str) -> None:
    """Write the main title and description block."""
    f.write('\n<h1 align="center">📜 Paper-List-DAILY</h1>\n')
    f.write('<p align="center"><strong>Automatically track & organize the latest arXiv papers by topic — updated daily via GitHub Actions</strong></p>\n')
    f.write('\n<p align="center">')
    f.write('<a href="https://islinxu.github.io/paper-list/"><img alt="Website" src="https://img.shields.io/badge/🌐_Live_Site-Visit_Now-0f4c5c?style=for-the-badge"></a> ')
    f.write('<a href="https://github.com/isLinXu/paper-list/stargazers"><img alt="Stargazers" src="https://img.shields.io/badge/⭐_Star_Us-ff6b6b?style=for-the-badge"></a>')
    f.write('</p>\n')
    f.write('\n---\n')
    f.write(f'\n> **📅 Last Updated:** `{date_now}` · **🤖 Auto-generated by GitHub Actions**\n')


def write_introduction_section(f) -> None:
    """Write the Introduction section."""
    f.write("\n## 📖 Introduction\n\n")
    f.write("**Paper-List-DAILY** is an automated arXiv paper tracking system that fetches, categorizes, and organizes the latest research papers across **20+ computer vision & AI topics** — from classic tasks like Object Detection and Segmentation to cutting-edge fields like Diffusion Models, LLMs, and Embodied AI.\n\n")
    f.write("Every day, GitHub Actions automatically polls the [Papers with Code API](https://paperswithcode.com/), enriches paper metadata with arXiv links, translation services, and code repositories, then generates beautifully formatted Markdown lists for both GitHub README and GitHub Pages.\n\n")
    f.write("🌐 **Online Documentation:** [https://islinxu.github.io/paper-list/](https://islinxu.github.io/paper-list/)\n\n")


def write_features_section(f) -> None:
    """Write the Features table."""
    f.write("## ✨ Features\n\n")
    f.write("| Feature | Description |\n")
    f.write("|---------|-------------|\n")
    f.write("| 🔄 **Daily Auto-Update** | Runs every 8 hours via GitHub Actions — zero manual intervention |\n")
    f.write("| 📂 **20+ Research Topics** | From Classification to Embodied AI, covering the full CV/AI spectrum |\n")
    f.write("| 📊 **Research Insights Entry** | Trend charts, topic rankings, top authors, and code coverage in a separate analytics section |\n")
    f.write("| 🔗 **Smart Link Enrichment** | Auto-attaches arXiv PDF, translation (papers.cool), reading (hjfy), and code links |\n")
    f.write("| 📱 **Dual Output** | Generates both GitHub README and Jekyll-powered GitHub Pages |\n")
    f.write("| 🤖 **Dual Reading Modes** | GitHub Pages supports both a human-facing view and a compact `?view=agent` mode |\n")
    f.write("| 🎨 **Three Visual Themes** | Editorial (warm), Atlas (dark), Lab (clean) — switchable on the site |\n")
    f.write("| 🔍 **Configurable Keywords** | Fully customizable search filters via `config.yaml` |\n")
    f.write("| 📈 **Monthly Archives** | Papers organized by month for easy historical browsing |\n")
    f.write("| 🌐 **Multi-language Support** | Integrated paper translation links for non-English readers |\n\n")


def write_workflow_section(f) -> None:
    """Write the How It Works section with ASCII diagram."""
    f.write("## 🏗️ How It Works\n\n")
    f.write("```\n┌─────────────────┐     ┌─────────────────┐     ┌─────────────────┐\n")
    f.write("│  Papers with    │────▶│  GitHub Actions │────▶│  Enriched MD    │\n")
    f.write("│  Code API       │     │  (every 8h)     │     │  + Analytics    │\n")
    f.write("└─────────────────┘     └─────────────────┘     └─────────────────┘\n")
    f.write("         │                       │                       │\n")
    f.write("         ▼                       ▼                       ▼\n")
    f.write("   📥 Fetch Papers        🔗 Enrich Links         📝 Generate\n")
    f.write("   🔍 Filter by Topic     📊 Build Analytics      🌐 GitHub Pages\n")
    f.write("   📅 Sort by Date        💾 Store JSON           📄 README.md\n")
    f.write("```\n\n")
    f.write("## 🧭 Reading Paths\n\n")
    f.write("- **Topic-first path:** Start from the live site homepage, choose a topic lane, enter a topic hub, then open a monthly archive.\n")
    f.write("- **Dense scan path:** Open `paper_list.html` when you want one continuous all-topics stream and prefer browser search.\n")
    f.write("- **Analytics path:** Open the separate insights dashboard only when you specifically want charts, rankings, and code coverage.\n")
    f.write("- **Agent path:** Add `?view=agent` on GitHub Pages for a denser, lower-noise reading mode with faster scanning.\n\n")


def write_quickstart_section(f) -> None:
    """Write the Quick Start section."""
    f.write("## 🚀 Quick Start\n\n")
    f.write("### Prerequisites\n\n")
    f.write("- Python 3.10+\n")
    f.write("- pip\n\n")
    f.write("### Installation\n\n")
    f.write("1. **Clone the repository**\n")
    f.write("   ```bash\n")
    f.write("   git clone https://github.com/isLinXu/paper-list.git\n")
    f.write("   cd paper-list\n")
    f.write("   ```\n\n")
    f.write("2. **Install Dependencies**\n")
    f.write("   ```bash\n")
    f.write("   pip install -r requirements.txt\n")
    f.write("   ```\n\n")
    f.write("3. **Run the Script**\n")
    f.write("   ```bash\n")
    f.write("   # Fetch papers from the last 2 days\n")
    f.write("   python get_paper.py\n\n")
    f.write("   # Or specify a date range\n")
    f.write("   python get_paper.py --start_date 2024-01-01 --end_date 2024-12-31\n")
    f.write("   ```\n\n")
    f.write("4. **Configuration**\n")
    f.write("   Customize search keywords, output paths, and more in [`config.yaml`](config.yaml):\n")
    f.write("   ```yaml\n")
    f.write("   keywords:\n")
    f.write("     \"Object Detection\":\n")
    f.write("       filters: [\"Object Detection\", \"2D Object Detection\", \"3D Object Detection\"]\n")
    f.write("     \"Diffusion Models\":\n")
    f.write("       filters: [\"Diffusion Model\", \"Stable Diffusion\", \"DALL-E\"]\n")
    f.write("   ```\n\n")
    f.write("### 🔧 Advanced Usage\n\n")
    f.write("| Command | Description |\n")
    f.write("|---------|-------------|\n")
    f.write("| `python get_paper.py --update_paper_links` | Enrich existing papers with code links |\n")
    f.write("| `python scripts/count_range.py 2024-01-01 2024-12-31` | Count papers in a date range |\n")
    f.write("| `python scripts/build_analytics.py --store docs/data --out docs/analytics` | Build the separate research insights dashboard |\n")
    f.write("| `./scripts/serve_pages.sh` | Install local Jekyll deps and preview GitHub Pages at `127.0.0.1:4000` |\n")
    f.write("| `python regenerate_readme.py` | Regenerate README from existing JSON data |\n\n")


def write_paper_table(f, day_content: dict, to_web: bool, use_title: bool) -> None:
    """Write a paper table for a single topic."""
    if use_title:
        if not to_web:
            f.write("|Publish Date|Title|Authors|PDF|Translate|Read|Code|\n|---|---|---|---|---|---|---|\n")
        else:
            f.write("| Publish Date | Title | Authors | PDF | Translate | Read | Code |\n")
            f.write("|:---------|:-----------------------|:---------|:------|:------|:------|:------|\n")

    for _, v in sort_papers(day_content).items():
        if v is not None:
            line = render_paper_row(v, emphasize=False) if isinstance(v, dict) else str(v)
            f.write(pretty_math(line))


def write_monthly_archive(topic: str, day_content: dict, topic_meta: dict,
                          to_web: bool, use_title: bool) -> None:
    """Write per-topic monthly archive files under docs/."""
    if not os.path.exists("docs"):
        os.makedirs("docs")

    kw = topic.replace(" ", "_")
    grouped = group_papers_by_month(day_content)
    total_papers = sum(len(month_items) for month_items in grouped.values())
    months_sorted = sorted(grouped.items(), reverse=True)
    latest_month, latest_items = months_sorted[0]
    meta = topic_meta.get(topic, {})
    lane_title = meta.get("lane_title", "Research Track")
    lane_eyebrow = meta.get("lane_eyebrow", "Topic Lane")
    prev_topic = meta.get("prev")
    next_topic = meta.get("next")

    with open(f"docs/{kw}.md", "w+") as f_sub:
        f_sub.write(f"## {topic}\n\n")
        f_sub.write(f"Lane: **{lane_title}**\n\n")
        f_sub.write(f"Total papers: **{total_papers}**\n\n")
        f_sub.write(f"Latest archive month: **{latest_month}** ({len(latest_items)} papers)\n\n")

        if prev_topic or next_topic:
            f_sub.write("Topic neighbors: ")
            parts = []
            if prev_topic:
                prev_href = prev_topic.replace(" ", "_") + ".md"
                parts.append(f"[← {prev_topic}]({prev_href})")
            if next_topic:
                next_href = next_topic.replace(" ", "_") + ".md"
                parts.append(f"[{next_topic} →]({next_href})")
            f_sub.write(" · ".join(parts) + "\n\n")

        f_sub.write(f"### {lane_eyebrow}\n\n")
        f_sub.write(f"This page is the monthly archive hub for **{topic}**. Start with the latest month if you want the freshest papers, or move down the list when you are tracing the topic over time.\n\n")
        f_sub.write("## Monthly Archives\n\n")

        for month, month_items in sorted(grouped.items(), reverse=True):
            month_dir = os.path.join("docs", kw)
            os.makedirs(month_dir, exist_ok=True)
            month_file = os.path.join(month_dir, f"{month}.md")
            month_href = f"{kw}/{month}.md"
            f_sub.write(f"- [{month}]({month_href}) ({len(month_items)} papers)\n")

            with open(month_file, "w+") as month_sub:
                month_sub.write(f"## {topic} - {month}\n\n")
                month_sub.write(f"Topic lane: **{lane_title}**\n\n")
                month_sub.write(f"Monthly papers: **{len(month_items)}**\n\n")
                if month == latest_month:
                    month_sub.write("This is the latest archive slice for this topic.\n\n")
                else:
                    month_sub.write(f"Latest available archive for this topic: **{latest_month}**\n\n")
                if use_title:
                    if not to_web:
                        month_sub.write("|Publish Date|Title|Authors|PDF|Translate|Read|Code|\n|---|---|---|---|---|---|---|\n")
                    else:
                        month_sub.write("| Publish Date | Title | Authors | PDF | Translate | Read | Code |\n")
                        month_sub.write("|:---------|:-----------------------|:---------|:------|:------|:------|:------|\n")

                for _, v in sort_papers(month_items).items():
                    if v is not None:
                        line = render_paper_row(v, emphasize=False) if isinstance(v, dict) else str(v)
                        month_sub.write(pretty_math(line))

                month_sub.write(f"\n<p align=right>(<a href=../{kw}.md>back to {topic}</a>)</p>\n\n")

        back_target = "index.md" if to_web else "../README.md"
        f_sub.write(f"\n<p align=right>(<a href={back_target}>back to main</a>)</p>\n\n")


def write_footer_sections(f, to_web: bool) -> None:
    """Write the footer sections: Insights, Star History, Contributing, License, Acknowledgements."""
    if to_web:
        analytics_href = "analytics/"
        charts_prefix = "analytics/charts/"
    else:
        analytics_href = "docs/analytics/"
        charts_prefix = "docs/analytics/charts/"

    f.write("\n---\n\n")
    f.write("## 📊 Research Insights\n\n")
    f.write("Analytics is available as a separate entrance so the main reading flow stays topic-first.\n\n")
    f.write(f"- **Insights Dashboard:** [{analytics_href}]({analytics_href})\n")
    f.write("- **Daily Trend:** Papers published per day\n")
    f.write("- **Topic Ranking:** Most active research areas\n")
    f.write("- **Top Authors:** Most prolific researchers\n")
    f.write("- **Code Coverage:** Ratio of papers with open-source code\n\n")
    f.write("<details>\n")
    f.write("<summary>Preview charts</summary>\n\n")
    f.write(f"![trend_daily]({charts_prefix}trend_daily.png)\n\n")
    f.write(f"![topic_rank]({charts_prefix}topic_rank.png)\n\n")
    f.write("</details>\n\n")

    f.write("\n---\n\n")
    f.write("## ⭐ Star History\n\n")
    f.write("[![Star History Chart](https://api.star-history.com/svg?repos=isLinXu/paper-list&type=Date)](https://star-history.com/#isLinXu/paper-list&Date)\n\n")
    f.write("> If you find this project helpful, please consider giving it a ⭐ — it helps others discover the project!\n\n")

    f.write("\n---\n\n")
    f.write("## 🤝 Contributing\n\n")
    f.write("We welcome contributions! Here are some ways you can help:\n\n")
    f.write("- **🐛 Report Issues:** Found a bug or missing paper? [Open an issue](https://github.com/isLinXu/paper-list/issues)\n")
    f.write("- **💡 Suggest Topics:** Want a new research category? Propose it in the issues\n")
    f.write("- **🔧 Improve Code:** Submit a PR to enhance the scraper, analytics, or UI\n")
    f.write("- **📖 Improve Docs:** Help us write better documentation\n\n")
    f.write("### Development Setup\n\n")
    f.write("```bash\n")
    f.write("# Fork and clone\n")
    f.write("git clone https://github.com/<your-username>/paper-list.git\n")
    f.write("cd paper-list\n\n")
    f.write("# Install dependencies\n")
    f.write("pip install -r requirements.txt\n\n")
    f.write("# Run tests\n")
    f.write("python -m pytest tests/\n")
    f.write("```\n\n")

    f.write("\n---\n\n")
    f.write("## 📄 License\n\n")
    f.write("This project is licensed under the [Apache License 2.0](LICENSE).\n\n")
    f.write("The paper data is sourced from [arXiv](https://arxiv.org/) and [Papers with Code](https://paperswithcode.com/), ")
    f.write("and remains subject to their respective terms of use.\n\n")

    f.write("\n---\n\n")
    f.write("## 🙏 Acknowledgements\n\n")
    f.write("- [arXiv](https://arxiv.org/) — for providing open access to research papers\n")
    f.write("- [Papers with Code](https://paperswithcode.com/) — for the comprehensive paper API\n")
    f.write("- [papers.cool](https://papers.cool/) — for paper translation services\n")
    f.write("- [hjfy.top](https://hjfy.top/) — for enhanced paper reading experience\n\n")

    f.write("\n---\n\n")
    f.write('<p align="center">\n')
    f.write('  <sub>Built with ❤️ by <a href="https://github.com/isLinXu">@isLinXu</a> · Powered by GitHub Actions</sub>\n')
    f.write("</p>\n")
