import argparse
import os
import sys
import time
from pathlib import Path

import requests

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from utils.pwc_archive import dump_json, load_json, manifest_row_filename


def fetch_archive_html(archive_url: str, max_retries: int = 3, backoff_seconds: float = 2.0) -> tuple[str, str]:
    last_error = None
    for attempt in range(max_retries):
        response = requests.get(
            archive_url,
            timeout=45,
            headers={"User-Agent": "paper-list/1.0", "Accept": "text/html,application/xhtml+xml"},
        )
        if response.status_code != 429:
            response.raise_for_status()
            return response.text, response.url
        last_error = requests.HTTPError(f"429 Client Error: Too Many Requests for url: {response.url}", response=response)
        retry_after = response.headers.get("Retry-After")
        sleep_seconds = float(retry_after) if retry_after else backoff_seconds * (attempt + 1)
        time.sleep(sleep_seconds)
    if last_error:
        raise last_error
    raise RuntimeError(f"Unable to fetch archive URL: {archive_url}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Fetch archived PapersWithCode HTML pages from a manifest.")
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("data/pwc_archive/staging/cdx_manifest.json"),
        help="Manifest JSON generated by pwc_cdx_discover.py or pwc_discover.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/pwc_archive/raw/html"),
        help="Directory for archived HTML files.",
    )
    parser.add_argument("--limit", type=int, default=20, help="Maximum number of rows to fetch in one run.")
    parser.add_argument("--entity-type", default=None, help="Optional entity type filter, e.g. paper")
    parser.add_argument("--sleep-seconds", type=float, default=1.0, help="Delay between requests.")
    parser.add_argument("--max-retries", type=int, default=3, help="Retry count for 429 or transient fetch failures.")
    parser.add_argument("--continue-on-error", action="store_true", help="Skip archive pages that fail to fetch.")
    parser.add_argument(
        "--state-output",
        type=Path,
        default=Path("data/pwc_archive/staging/fetch_state.json"),
        help="Output JSON file describing fetched rows.",
    )
    args = parser.parse_args()

    manifest = load_json(args.manifest, [])
    args.output_dir.mkdir(parents=True, exist_ok=True)
    fetched_rows = []
    count = 0
    success_count = 0
    cached_count = 0
    error_count = 0

    for row in manifest:
        if args.entity_type and row.get("entity_type") != args.entity_type:
            continue
        if count >= args.limit:
            break

        output_path = args.output_dir / manifest_row_filename(row)
        if output_path.exists():
            fetched_rows.append({**row, "raw_html_path": str(output_path), "fetch_status": "cached"})
            count += 1
            cached_count += 1
            continue

        try:
            html, final_url = fetch_archive_html(row["archive_url"], max_retries=args.max_retries)
        except requests.RequestException as exc:
            fetched_rows.append({**row, "fetch_status": "error", "error": str(exc)})
            count += 1
            error_count += 1
            if not args.continue_on_error:
                raise
            continue
        output_path.write_text(html, encoding="utf-8")
        fetched_rows.append({**row, "raw_html_path": str(output_path), "archive_url": final_url, "fetch_status": "fetched"})
        count += 1
        success_count += 1
        time.sleep(args.sleep_seconds)

    dump_json(args.state_output, fetched_rows)
    print(
        f"Archive fetch summary: success={success_count}, cached={cached_count}, error={error_count}, total={len(fetched_rows)}"
    )


if __name__ == "__main__":
    main()
