title: Paper Arxiv Daily
description: Automatically Update Papers Daily using Github Actions (Update Every 8th hours)
show_downloads: true

github:
  zip_url: https://github.com/isLinXu/paper-list
  another_url: https://github.com/isLinXu/paper-list

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  twitter:
  github: isLinXu

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
